language: python
python:
- '2.7'
- '3.3'
- '3.4'
install:
- pip install -e .
- pip install coverage coveralls wheel
script:
- coverage run setup.py test
- coveralls
- coverage report --fail-under=100
deploy:
  provider: pypi
  distributions: "sdist bdist_wheel"
  user:
    secure: TrNX8WHlyfmj8aJfH6coB89SQiMJIHK33KH7Jtin7hPSCAjq2E5Cl9rK+jp5p9sllfEO4Ec8Cz5qmjD7ziQe3aqy92i+9vtsiaAvVE9yOLWbo27UZLxdf/cOUiAOIwQJ/LCfETjP75abUfhskb2DSB9Tl6IvWBh5PCji4K+QBm4=
  password:
    secure: RqrfUlEOUmqUWTI6BbVw0O7Jo9lrmp7ZxMrsFTEjGmTzPKu/wWrHkIN11ImIN6A95AbHujYKcFLj3CQ0r3o9X3IFwQtMnFn6Yd7zGg39rfDO1esTxm5i0tJhshaTpIY4GrhF3e/DfHWFjA4DdtUyOmdTbTSzLila0aKWKkkehj4=
  on:
    python: 2.7
    tags: true
    repo: pyembed/pyembed-mustache
